name = "FMIBase"
uuid = "900ee838-d029-460e-b485-d98a826ceef2"
authors = ["TT <tobias.thummerer@informatik.uni-augsburg.de>", "LM <lars.mikelsons@informatik.uni-augsburg.de>"]
version = "1.0.2"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FMICore = "8af89139-c281-408e-bce2-3005eb87462f"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[weakdeps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[extensions]
CSVExt = ["CSV"]
DataFramesExt = ["DataFrames"]
ForwardDiffExt = ["ForwardDiff"]
JLD2Ext = ["JLD2"]
MATExt = ["MAT"]
PlotsExt = ["Plots"]
ReverseDiffExt = ["ReverseDiff"]

[compat]
CSV = "0.10"
ChainRulesCore = "1.20 - 1.23, 1"
DataFrames = "1"
DiffEqCallbacks = "2.0 - 3.6"
EzXML = "1.1 - 1.2"
FMICore = "1.0.1"
ForwardDiff = "0.10"
JLD2 = "0.4"
MAT = "0.10"
PackageExtensionCompat = "1.0.0"
Plots = "1"
ProgressMeter = "1.7"
Reexport = "1.0 - 1.2"
Requires = "1.3.0"
ReverseDiff = "1"
SciMLBase = "1.0, 2.0"
ZipFile = "0.10.0"
julia = "1.6"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
